export const creationButtonLabels = [
  'registrar hogar',
  'registrar nuevo hogar',
  'registrar dispositivo',
  'registrar nuevo dispositivo',
  'agregar hogar',
  'agregar nuevo hogar',
  'agregar dispositivo',
  'agregar nuevo dispositivo',
  'add home',
  'add new home',
  'add device',
  'add new device',
  'register home',
  'register new home',
  'register device',
  'register new device',
  'new home',
  'new device',
  'novo lar',
  'novo dispositivo',
  'nuova casa',
  'nuovo dispositivo',
];
